name: Compile test

on:  [push, pull_request]

jobs:     
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [examples]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO
      run: platformio ci --lib="." --board=zeroUSB
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
        
    - name: Install Protoc
      uses: arduino/setup-protoc@1.1.0
      with:
        version: 3.x
        include-pre-release: false
        repo-token: ${{ secrets.GITHUB_TOKEN }}


    - name: Run Arduino CLI
      run: |
        arduino-cli core update-index
        arduino-cli board listall zero
        echo "arduino-cli compile -b arduino:samd:zero"

      
