name: Compile test

on:  [push, pull_request]

jobs:     
  build-pio:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        example: [examples/empty_sketch.ino, examples/serial_blink.ino, examples/serial_timer.ino]
        boards: [zeroUSB]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO
      run: platformio ci --lib="." --board=${{ matrix.boards }}
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}




 arduino:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       fqbn: [
         "arduino:samd:zero"
       ]

   steps:
     - uses: actions/checkout@v1
       with:
         fetch-depth: 1
     - uses: arduino/actions/libraries/compile-examples@master
       with:
         fqbn: ${{ matrix.fqbn }}
