name: Compile test

on:  [push, pull_request]

jobs:     
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [examples]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO
      run: platformio ci --lib="." --board=zeroUSB
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0

    - name: Run Arduino CLI
      run: |
        arduino-cli board listall zero
        echo "arduino-cli compile -b arduino:samd:zero"

      
